[package]
name = "tor-client"
version = "0.1.0"
edition = "2024"

[dependencies]
simple_socks5 = "0.1"
tokio = { version = "1.47.1", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
